import { type NextPage } from "next";
import React from "react";
import { MainLinks } from "@/components/shell/_main-links";
import { User } from "@/components/shell/_user";
import Head from "next/head";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main>
        <User />
        <MainLinks />
        <h1>Dashboard</h1>
      </main>
    </>
  );
};

export default Dashboard;
