import AdminDashboardLayout from "@/components/layouts/admin-dashboard-layout";
import { type NextPage } from "next";
import Head from "next/head";
import React from "react";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main>
        <AdminDashboardLayout>Dashboard</AdminDashboardLayout>
      </main>
    </>
  );
};

export default Dashboard;
