import AdminDashboardLayout from "@/components/layouts/admin-dashboard-layout";
import { MainLinks } from "@/components/shell/_main-links";
import { User } from "@/components/shell/_user";
import { type NextPage } from "next";
import Head from "next/head";
import React from "react";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main>
        <AdminDashboardLayout>
          <h1>Dashboard</h1>
        </AdminDashboardLayout>
      </main>
    </>
  );
};

export default Dashboard;
