import { api } from "@/utils/api";
import { Course } from "@prisma/client";
import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FC, useState } from "react";

const Courses: NextPage = () => {
  const courses = api.course.getCourses.useQuery();
  const createCourseMutation = api.course.createCourse.useMutation();

  const [title, setTitle] = useState();
  const [description, setDescription] = useState();

  const handleSubmitCourse = async () => {
    await createCourseMutation.mutateAsync({
      title,
      description,
    });
    courses.refetch();
  };
  return (
    <>
      <Head>
        <title>Manage Courses</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main>
        <div>
          <h2>Modal</h2>
          <form onSubmit={handleSubmitCourse}>
            <input
              aria-label="title"
              placeholder="name your course here"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              aria-label="description"
              placeholder="describe your course a bit"
            />
            <button type="submit">Create Course</button>
          </form>
        </div>

        <h1>Manage Courses</h1>
        {courses.map((course) => (
          <CourseCard course={course} />
        ))}
      </main>
    </>
  );
};

const CourseCard: FC<{ course: Course }> = ({ course }) => {
  return (
    <div>
      <Image src={course.imageId} alt={course.title} />
      <h2>{course.title}</h2>
      <p>{course.description}</p>
      <Link href={`/dashboard/courses/${course.id}`}>Manage</Link>
    </div>
  );
};

export default Courses;
