import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> landing page</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main>LANDING PAGE</main>
    </>
  );
};

export default Home;
